# ============================================================
# 情報系データ
# ローカルディレクトリ → S3 Prefix 対応表
#
# 形式：
#
# ローカルディレクトリ名|S3プレフィックス名
#
# ※実際の対象テーブルに合わせて追記・修正すること
# ============================================================


B42030|B42030

P01050_AF|P01050_AF

P01060_AG|P01060_AG

P01060_AH|P01060_AH

P01070_AL|P01070_AL

P01071_AM|P01071_AM

P03010_DA|P03010_DA

P03020_DB|P03020_DB
