# ============================================================
# 情報系データ S3転送 Mapping
#
# Format:
# FILE_NAME_PREFIX|S3_PREFIX
#
# ※ _001.csv.gz 等の連番部分は記載しない
# ※ S3_PREFIXは「自由検索テーブル一覧」の
#   「プレフィックス(Raw)」を正とする
# ============================================================

AA_昇降機情報|P01010_AA
AB_昇降機付加装置情報|P01011_AB
AF_建物情報|P01050_AF
AG_保守契約情報|P01060_AG
AH_昇降機保守契約情報|P01060_AH
AI_点検保守契約情報|P01065_AI
AL_工事契約情報|P01070_AL
AM_工事受注情報|P01071_AM
BL_工事経歴情報|P01140_BL
DA_顧客改造情報|P03010_DA
DB_顧客改造現場情報|P03020_DB
FL_出庫明細情報|P05120_FL
FP_品番マスター情報|P05160_FP

# XAA_昇降機情報_蓄積：
# SourceはAA_昇降機情報と同一のため転送対象外

# XFL_出庫明細情報_蓄積：
# SourceはFL_出庫明細情報と同一のため転送対象外

Z_B42030_稲電オーダ情報|B42030
Z_B72010_Fオーダ管理情報|B72010
Z_B72210_F作業実績情報|B72210
Z_B72220_F作業実績_作業内容|B72220
Z_D21140_部品要求明細_機能維持|D21140
Z_D38689_昇降機稼働量データ|D38689
Z_G10050_部品要求明細|G10050
