# ============================================================
# 情報系データ 転送Mapping
#
# Format:
# ENABLE|SOURCE_USER|SOURCE_HOST|SOURCE_PORT|REMOTE_DIR|FILE_NAME_PREFIX|S3_PREFIX
#
# ENABLE
#   Y : 処理対象
#   N : 処理対象外
#
# SOURCE_USER / HOST / PORT / REMOTE_DIR
#   【実機担当設定】
#
# FILE_NAME_PREFIX
#   自由検索テーブル一覧のファイル名より設定
#   _001.csv.gz 等の連番部分は記載しない
#
# S3_PREFIX
#   自由検索テーブル一覧の「プレフィックス(Raw)」より設定
# ============================================================


# ↓ 接続先情報は実機環境に合わせて設定

Y|PLEASE_SET_USER|PLEASE_SET_HOST|22|PLEASE_SET_REMOTE_DIR|AA_昇降機情報|P01010_AA
Y|PLEASE_SET_USER|PLEASE_SET_HOST|22|PLEASE_SET_REMOTE_DIR|AB_昇降機付加装置情報|P01011_AB
Y|PLEASE_SET_USER|PLEASE_SET_HOST|22|PLEASE_SET_REMOTE_DIR|AF_建物情報|P01050_AF
Y|PLEASE_SET_USER|PLEASE_SET_HOST|22|PLEASE_SET_REMOTE_DIR|AG_保守契約情報|P01060_AG
Y|PLEASE_SET_USER|PLEASE_SET_HOST|22|PLEASE_SET_REMOTE_DIR|AH_昇降機保守契約情報|P01060_AH

# XAA / XFL 蓄積系はSourceが既存テーブルと同一のため対象外
